/*
 * This source file was generated by the Gradle 'init' task
 */

import controller.OrderController;
import org.json.simple.parser.ParseException;

import java.io.IOException;

public class App {

    public static void main(String[] args) throws IOException, ParseException {
        OrderController orderController = new OrderController();
        orderController.startOrder();
    }
}
